version: '3.7'
services:
  api:
    build: ./app
    restart: always
    ports:
      - 5000:8000
    volumes:
      - /static:/code/app/static
      - /home/gon2gon2/git/server/app/endpoints:/code/app/endpoints