version: '3.7'
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile-deploy
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - /static:/code/app/static
    deploy: 
      resources: 
        reservations: 
          devices: 
            - driver: nvidia 
              count: 1 
              capabilities: [gpu, utility]

