version: '3.7'
services:
  api:
    build: ./app
    restart: always
    ports:
      - 5000:8000
    volumes:
      - ./static:/code/app/static
      - ./app/endpoints:/code/app/endpoints
      - ./app/models:/code/app/models
      - ./app/schemas:/code/app/schemas