version: '3.7'
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile-deploy
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - /mnt/server/app:/code/app
      - /static:/code/app/static
    environment:
      - NVIDIA_VISIBLE_DEVICES=all